# Contents of this file under shared license
defaults: &defaults
  adapter: postgresql
  username: whatwouldyoudo
  password: whatwouldyoudo
  encoding: unicode
  pool: 5
  host: localhost
development:
  <<: *defaults
  database: whatwouldyoudo
test: &test
  <<: *defaults
  database: whatwouldyoudo_test
